import type { Metadata } from "next";
import "./styles/globals.css";
import { Rubik } from "next/font/google"

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik',
})

export const metadata: Metadata = {
  title: "Konrad's Time tracking Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${rubik.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
